# Generated by Django 3.2 on 2022-11-12 17:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_patients_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\SAHAJ\\Desktop\\Project\\Environments\\env\\src\\healthdash\\media'), upload_to='')),
            ],
        ),
    ]
