# Generated by Django 3.2 on 2022-11-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_pdf_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf_upload',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='pdf_upload',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
