# Generated by Django 3.2 on 2022-11-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodtype',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='A+', max_length=3),
        ),
    ]
