# Generated by Django 3.2 on 2022-11-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_patient_bloodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='No Allergies', max_length=100),
        ),
    ]
