# Generated by Django 3.2 on 2022-11-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_patient_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diseases',
            field=models.CharField(default='No Diseases', max_length=100),
        ),
    ]
