# Generated by Django 3.2 on 2022-12-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20221115_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='color',
            field=models.CharField(choices=[('Green', 'GREEN'), ('Orange', 'ORANGE'), ('Red', 'RED')], default='Green', max_length=8),
        ),
    ]
