# Generated by Django 3.2 on 2023-07-20 03:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_patient_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_upload',
            name='pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/charon/Desktop/Sandbox/ELCSummer2023-main/media'), upload_to=''),
        ),
    ]
